version: '3.7'
services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "54321:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_LOGIN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/psql/data
  
volumes:
  postgres_data: