name: CodeFormatter

on:
  push:
    branches: [main]

jobs:
  formatting:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6
        
    - name: Install pip and poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install Dependences
      run: |
        poetry install

    - name: Install pylint
      run: |
        poetry add pylint
        
    - name: Analysing the code with pylint
      run: |
        pylint .

    - name: Apply black
      run: |
       black .
